CREATE INDEX "business_files_tenant_idx" ON "business_files" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "managed_files_tenant_idx" ON "managed_files" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "upload_sessions_tenant_idx" ON "upload_sessions" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "export_job_downloads_tenant_idx" ON "export_job_downloads" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "login_logs_tenant_idx" ON "login_logs" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "operation_logs_tenant_idx" ON "operation_logs" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "analytics_user_profiles_tenant_idx" ON "analytics_user_profiles" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "announcements_tenant_idx" ON "announcements" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "workflow_automations_tenant_idx" ON "workflow_automations" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "workflow_comments_tenant_idx" ON "workflow_comments" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "workflow_compensation_logs_tenant_idx" ON "workflow_compensation_logs" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "workflow_compensations_tenant_idx" ON "workflow_compensations" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "workflow_definition_versions_tenant_idx" ON "workflow_definition_versions" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "workflow_delegations_tenant_idx" ON "workflow_delegations" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "workflow_event_subscriptions_tenant_idx" ON "workflow_event_subscriptions" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "workflow_instance_migrations_tenant_idx" ON "workflow_instance_migrations" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "workflow_job_executions_tenant_idx" ON "workflow_job_executions" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "workflow_jobs_tenant_idx" ON "workflow_jobs" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "workflow_quick_phrases_tenant_idx" ON "workflow_quick_phrases" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "workflow_saved_views_tenant_idx" ON "workflow_saved_views" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "workflow_schedules_tenant_idx" ON "workflow_schedules" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "workflow_simulation_cases_tenant_idx" ON "workflow_simulation_cases" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "workflow_task_consults_tenant_idx" ON "workflow_task_consults" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "workflow_task_transfers_tenant_idx" ON "workflow_task_transfers" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "workflow_templates_tenant_idx" ON "workflow_templates" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "workflow_tokens_tenant_idx" ON "workflow_tokens" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "email_send_logs_tenant_idx" ON "email_send_logs" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "email_templates_tenant_idx" ON "email_templates" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "in_app_messages_tenant_idx" ON "in_app_messages" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "in_app_templates_tenant_idx" ON "in_app_templates" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "sms_configs_tenant_idx" ON "sms_configs" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "sms_send_logs_tenant_idx" ON "sms_send_logs" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "sms_templates_tenant_idx" ON "sms_templates" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "rule_decision_executions_tenant_idx" ON "rule_decision_executions" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "rule_decision_table_versions_tenant_idx" ON "rule_decision_table_versions" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "rule_test_cases_tenant_idx" ON "rule_test_cases" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "biz_leaves_tenant_idx" ON "biz_leaves" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "biz_pay_demos_tenant_idx" ON "biz_pay_demos" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "chat_conversations_tenant_idx" ON "chat_conversations" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "chat_webhooks_tenant_idx" ON "chat_webhooks" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "channels_tenant_idx" ON "channels" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_accounts_tenant_idx" ON "payment_accounts" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_apps_tenant_idx" ON "payment_apps" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_channel_configs_tenant_idx" ON "payment_channel_configs" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_contracts_tenant_idx" ON "payment_contracts" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_deduct_plans_tenant_idx" ON "payment_deduct_plans" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_disputes_tenant_idx" ON "payment_disputes" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_events_tenant_idx" ON "payment_events" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_fee_rules_tenant_idx" ON "payment_fee_rules" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_ledger_entries_tenant_idx" ON "payment_ledger_entries" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_links_tenant_idx" ON "payment_links" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_method_configs_tenant_idx" ON "payment_method_configs" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_notify_logs_tenant_idx" ON "payment_notify_logs" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_orders_tenant_idx" ON "payment_orders" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_preauths_tenant_idx" ON "payment_preauths" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_recon_batches_tenant_idx" ON "payment_recon_batches" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_refunds_tenant_idx" ON "payment_refunds" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_report_daily_tenant_idx" ON "payment_report_daily" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_risk_hits_tenant_idx" ON "payment_risk_hits" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_risk_reviews_tenant_idx" ON "payment_risk_reviews" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_risk_rules_tenant_idx" ON "payment_risk_rules" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_settlement_batches_tenant_idx" ON "payment_settlement_batches" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_sharing_orders_tenant_idx" ON "payment_sharing_orders" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_sharing_receivers_tenant_idx" ON "payment_sharing_receivers" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_transfers_tenant_idx" ON "payment_transfers" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_webhook_deliveries_tenant_idx" ON "payment_webhook_deliveries" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "payment_webhook_endpoints_tenant_idx" ON "payment_webhook_endpoints" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "ai_conversations_tenant_idx" ON "ai_conversations" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "terminal_recordings_tenant_idx" ON "terminal_recordings" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "coupons_tenant_idx" ON "coupons" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "members_tenant_idx" ON "members" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "mp_auto_replies_tenant_idx" ON "mp_auto_replies" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "mp_broadcasts_tenant_idx" ON "mp_broadcasts" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "mp_conditional_menus_tenant_idx" ON "mp_conditional_menus" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "mp_drafts_tenant_idx" ON "mp_drafts" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "mp_fans_tenant_idx" ON "mp_fans" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "mp_kf_accounts_tenant_idx" ON "mp_kf_accounts" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "mp_kf_routing_configs_tenant_idx" ON "mp_kf_routing_configs" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "mp_kf_session_events_tenant_idx" ON "mp_kf_session_events" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "mp_kf_sessions_tenant_idx" ON "mp_kf_sessions" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "mp_materials_tenant_idx" ON "mp_materials" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "mp_menus_tenant_idx" ON "mp_menus" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "mp_message_templates_tenant_idx" ON "mp_message_templates" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "mp_messages_tenant_idx" ON "mp_messages" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "mp_qrcodes_tenant_idx" ON "mp_qrcodes" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "mp_tags_tenant_idx" ON "mp_tags" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "mp_template_send_logs_tenant_idx" ON "mp_template_send_logs" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "mp_unmatched_keywords_tenant_idx" ON "mp_unmatched_keywords" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX "report_dataset_execution_logs_tenant_idx" ON "report_dataset_execution_logs" USING btree ("tenant_id");