CREATE INDEX "password_reset_tokens_user_idx" ON "password_reset_tokens" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "user_api_tokens_user_idx" ON "user_api_tokens" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "user_oauth_accounts_user_idx" ON "user_oauth_accounts" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "workflow_comments_user_idx" ON "workflow_comments" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "workflow_compensation_logs_operator_idx" ON "workflow_compensation_logs" USING btree ("operator_id");--> statement-breakpoint
CREATE INDEX "workflow_quick_phrases_user_idx" ON "workflow_quick_phrases" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "workflow_saved_views_user_idx" ON "workflow_saved_views" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "workflow_task_transfers_operator_idx" ON "workflow_task_transfers" USING btree ("operator_id");--> statement-breakpoint
CREATE INDEX "email_send_logs_user_idx" ON "email_send_logs" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "sms_send_logs_user_idx" ON "sms_send_logs" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "db_query_favorites_user_idx" ON "db_query_favorites" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "chat_message_reactions_user_idx" ON "chat_message_reactions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "channel_conversations_user_idx" ON "channel_conversations" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "channel_message_targets_user_idx" ON "channel_message_targets" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "channel_subscriptions_user_idx" ON "channel_subscriptions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "payment_dispute_replies_operator_idx" ON "payment_dispute_replies" USING btree ("operator_id");--> statement-breakpoint
CREATE INDEX "payment_orders_user_idx" ON "payment_orders" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "payment_preauths_operator_idx" ON "payment_preauths" USING btree ("operator_id");--> statement-breakpoint
CREATE INDEX "payment_refunds_operator_idx" ON "payment_refunds" USING btree ("operator_id");--> statement-breakpoint
CREATE INDEX "payment_risk_hits_user_idx" ON "payment_risk_hits" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "payment_transfers_operator_idx" ON "payment_transfers" USING btree ("operator_id");--> statement-breakpoint
CREATE INDEX "ai_agents_user_idx" ON "ai_agents" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "ai_arena_votes_user_idx" ON "ai_arena_votes" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "ai_conversations_user_idx" ON "ai_conversations" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "ai_knowledge_bases_user_idx" ON "ai_knowledge_bases" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "ai_prompt_templates_user_idx" ON "ai_prompt_templates" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "ai_shared_conversations_user_idx" ON "ai_shared_conversations" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "user_ai_configs_user_idx" ON "user_ai_configs" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "oauth2_authorization_codes_user_idx" ON "oauth2_authorization_codes" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "oauth2_tokens_user_idx" ON "oauth2_tokens" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "ssh_profiles_user_idx" ON "ssh_profiles" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "terminal_recordings_user_idx" ON "terminal_recordings" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "member_point_transactions_operator_idx" ON "member_point_transactions" USING btree ("operator_id");--> statement-breakpoint
CREATE INDEX "member_wallet_transactions_operator_idx" ON "member_wallet_transactions" USING btree ("operator_id");--> statement-breakpoint
CREATE INDEX "mp_kf_session_events_operator_idx" ON "mp_kf_session_events" USING btree ("operator_id");--> statement-breakpoint
CREATE INDEX "report_dashboard_comments_user_idx" ON "report_dashboard_comments" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "report_chatbi_messages_user_idx" ON "report_chatbi_messages" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "report_chatbi_sessions_user_idx" ON "report_chatbi_sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "cms_content_op_logs_operator_idx" ON "cms_content_op_logs" USING btree ("operator_id");--> statement-breakpoint
CREATE INDEX "cms_site_users_user_idx" ON "cms_site_users" USING btree ("user_id");