CREATE INDEX "dict_items_parent_idx" ON "dict_items" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX "workflow_automations_definition_idx" ON "workflow_automations" USING btree ("definition_id");--> statement-breakpoint
CREATE INDEX "workflow_comments_task_idx" ON "workflow_comments" USING btree ("task_id");--> statement-breakpoint
CREATE INDEX "workflow_comments_parent_idx" ON "workflow_comments" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX "workflow_comments_instance_idx" ON "workflow_comments" USING btree ("instance_id");--> statement-breakpoint
CREATE INDEX "workflow_delegations_definition_idx" ON "workflow_delegations" USING btree ("definition_id");--> statement-breakpoint
CREATE INDEX "workflow_event_subscriptions_definition_idx" ON "workflow_event_subscriptions" USING btree ("definition_id");--> statement-breakpoint
CREATE INDEX "workflow_instances_definition_idx" ON "workflow_instances" USING btree ("definition_id");--> statement-breakpoint
CREATE INDEX "workflow_jobs_task_idx" ON "workflow_jobs" USING btree ("task_id");--> statement-breakpoint
CREATE INDEX "workflow_schedules_definition_idx" ON "workflow_schedules" USING btree ("definition_id");--> statement-breakpoint
CREATE INDEX "workflow_task_consults_task_idx" ON "workflow_task_consults" USING btree ("task_id");--> statement-breakpoint
CREATE INDEX "workflow_task_consults_instance_idx" ON "workflow_task_consults" USING btree ("instance_id");--> statement-breakpoint
CREATE INDEX "workflow_task_urges_task_idx" ON "workflow_task_urges" USING btree ("task_id");--> statement-breakpoint
CREATE INDEX "workflow_task_urges_instance_idx" ON "workflow_task_urges" USING btree ("instance_id");--> statement-breakpoint
CREATE INDEX "chat_scheduled_messages_conversation_idx" ON "chat_scheduled_messages" USING btree ("conversation_id");--> statement-breakpoint
CREATE INDEX "chat_webhooks_conversation_idx" ON "chat_webhooks" USING btree ("conversation_id");--> statement-breakpoint
CREATE INDEX "channel_auto_replies_channel_idx" ON "channel_auto_replies" USING btree ("channel_id");--> statement-breakpoint
CREATE INDEX "channel_menus_channel_idx" ON "channel_menus" USING btree ("channel_id");--> statement-breakpoint
CREATE INDEX "channel_messages_channel_idx" ON "channel_messages" USING btree ("channel_id");--> statement-breakpoint
CREATE INDEX "channel_quick_replies_channel_idx" ON "channel_quick_replies" USING btree ("channel_id");--> statement-breakpoint
CREATE INDEX "payment_refunds_order_idx" ON "payment_refunds" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "ai_shared_conversations_conversation_idx" ON "ai_shared_conversations" USING btree ("conversation_id");--> statement-breakpoint
CREATE INDEX "cms_collect_items_content_idx" ON "cms_collect_items" USING btree ("content_id");--> statement-breakpoint
CREATE INDEX "cms_collect_rules_channel_idx" ON "cms_collect_rules" USING btree ("channel_id");--> statement-breakpoint
CREATE INDEX "cms_content_channels_channel_idx" ON "cms_content_channels" USING btree ("channel_id");--> statement-breakpoint
CREATE INDEX "cms_contents_channel_idx" ON "cms_contents" USING btree ("channel_id");--> statement-breakpoint
CREATE INDEX "cms_member_view_history_content_idx" ON "cms_member_view_history" USING btree ("content_id");--> statement-breakpoint
CREATE INDEX "cms_publish_artifacts_content_idx" ON "cms_publish_artifacts" USING btree ("content_id");--> statement-breakpoint
CREATE INDEX "cms_publish_artifacts_channel_idx" ON "cms_publish_artifacts" USING btree ("channel_id");--> statement-breakpoint
CREATE INDEX "cms_resource_folders_parent_idx" ON "cms_resource_folders" USING btree ("parent_id");