import type { Menu } from '../../identity/contracts';
import { SEED_DATE } from '../_base';

/** CMS 内容管理（14000 段） */
export const SEED_MENUS_CMS: Menu[] = [
  { id: 14000, parentId: 0, title: 'CMS 内容管理', name: 'CmsCenter', icon: 'Newspaper', type: 'directory', sort: 15, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14010, parentId: 14000, title: '数据看板', name: 'CmsDashboard', path: '/cms/dashboard', component: 'cms/CmsDashboardPage', icon: 'LayoutDashboard', type: 'menu', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14011, parentId: 14010, title: '查询', type: 'button', permission: 'cms:dashboard:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14020, parentId: 14000, title: '站点管理', name: 'CmsSites', path: '/cms/sites', component: 'cms/SitesPage', icon: 'Globe', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14021, parentId: 14020, title: '查询', type: 'button', permission: 'cms:site:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14022, parentId: 14020, title: '新增站点', type: 'button', permission: 'cms:site:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14023, parentId: 14020, title: '编辑站点', type: 'button', permission: 'cms:site:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14024, parentId: 14020, title: '删除站点', type: 'button', permission: 'cms:site:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14025, parentId: 14020, title: '全站静态化', type: 'button', permission: 'cms:publish:build', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14026, parentId: 14020, title: '管理站群层级', type: 'button', permission: 'cms:site:hierarchy', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14027, parentId: 14020, title: '站群批量发布', type: 'button', permission: 'cms:publish:group', sort: 6, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14030, parentId: 14000, title: '栏目管理', name: 'CmsChannels', path: '/cms/channels', component: 'cms/ChannelsPage', icon: 'FolderTree', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14031, parentId: 14030, title: '查询', type: 'button', permission: 'cms:channel:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14032, parentId: 14030, title: '新增栏目', type: 'button', permission: 'cms:channel:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14033, parentId: 14030, title: '编辑栏目', type: 'button', permission: 'cms:channel:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14034, parentId: 14030, title: '删除栏目', type: 'button', permission: 'cms:channel:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14040, parentId: 14000, title: '内容管理', name: 'CmsContents', path: '/cms/contents', component: 'cms/ContentsPage', icon: 'FileText', type: 'menu', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14041, parentId: 14040, title: '查询', type: 'button', permission: 'cms:content:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14042, parentId: 14040, title: '新增内容', type: 'button', permission: 'cms:content:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14043, parentId: 14040, title: '编辑内容', type: 'button', permission: 'cms:content:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14044, parentId: 14040, title: '删除内容', type: 'button', permission: 'cms:content:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14045, parentId: 14040, title: '发布内容', type: 'button', permission: 'cms:content:publish', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14046, parentId: 14040, title: '审核内容', type: 'button', permission: 'cms:content:audit', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14047, parentId: 14040, title: '锁定内容', type: 'button', permission: 'cms:content:lock', sort: 6, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14048, parentId: 14040, title: '导出内容', type: 'button', permission: 'cms:content:export', sort: 7, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14050, parentId: 14040, title: '内容编辑页', name: 'CmsContentEdit', path: '/cms/contents/edit', component: 'cms/ContentEditPage', icon: 'FilePen', type: 'menu', sort: 7, status: 'enabled', visible: false, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14051, parentId: 14050, title: '查询', type: 'button', permission: 'cms:content:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14060, parentId: 14000, title: '素材中心', name: 'CmsResources', path: '/cms/resources', component: 'cms/ResourcesPage', icon: 'Image', type: 'menu', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14061, parentId: 14060, title: '查询', type: 'button', permission: 'cms:resource:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14062, parentId: 14060, title: '上传素材', type: 'button', permission: 'cms:resource:upload', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14063, parentId: 14060, title: '编辑素材', type: 'button', permission: 'cms:resource:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14064, parentId: 14060, title: '删除素材', type: 'button', permission: 'cms:resource:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14070, parentId: 14000, title: '内容模型', name: 'CmsModels', path: '/cms/models', component: 'cms/ModelsPage', icon: 'Blocks', type: 'menu', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14071, parentId: 14070, title: '查询', type: 'button', permission: 'cms:model:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14072, parentId: 14070, title: '新增模型', type: 'button', permission: 'cms:model:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14073, parentId: 14070, title: '编辑模型', type: 'button', permission: 'cms:model:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14074, parentId: 14070, title: '删除模型', type: 'button', permission: 'cms:model:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14080, parentId: 14000, title: '标签管理', name: 'CmsTags', path: '/cms/tags', component: 'cms/TagsPage', icon: 'Tags', type: 'menu', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14081, parentId: 14080, title: '查询', type: 'button', permission: 'cms:tag:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14082, parentId: 14080, title: '新增标签', type: 'button', permission: 'cms:tag:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14083, parentId: 14080, title: '编辑标签', type: 'button', permission: 'cms:tag:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14084, parentId: 14080, title: '删除标签', type: 'button', permission: 'cms:tag:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14100, parentId: 14000, title: '友情链接', name: 'CmsFriendLinks', path: '/cms/friend-links', component: 'cms/FriendLinksPage', icon: 'Link2', type: 'menu', sort: 7, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14101, parentId: 14100, title: '查询', type: 'button', permission: 'cms:link:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14102, parentId: 14100, title: '新增友链', type: 'button', permission: 'cms:link:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14103, parentId: 14100, title: '编辑友链', type: 'button', permission: 'cms:link:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14104, parentId: 14100, title: '删除友链', type: 'button', permission: 'cms:link:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14110, parentId: 14000, title: '检索管理', name: 'CmsSearch', path: '/cms/search', component: 'cms/SearchAdminPage', icon: 'SearchCheck', type: 'menu', sort: 9, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14111, parentId: 14110, title: '查询', type: 'button', permission: 'cms:search:manage', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14120, parentId: 14000, title: 'SEO 管理', name: 'CmsSeo', path: '/cms/seo', component: 'cms/SeoPage', icon: 'TrendingUp', type: 'menu', sort: 10, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14121, parentId: 14120, title: '查询', type: 'button', permission: 'cms:seo:manage', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14122, parentId: 14120, title: '搜索引擎推送', type: 'button', permission: 'cms:seo:push', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14130, parentId: 14000, title: '评论管理', name: 'CmsComments', path: '/cms/comments', component: 'cms/CommentsPage', icon: 'MessageSquare', type: 'menu', sort: 11, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14131, parentId: 14130, title: '查询', type: 'button', permission: 'cms:comment:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14132, parentId: 14130, title: '审核评论', type: 'button', permission: 'cms:comment:audit', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14133, parentId: 14130, title: '删除评论', type: 'button', permission: 'cms:comment:delete', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14140, parentId: 14000, title: '广告管理', name: 'CmsAds', path: '/cms/ads', component: 'cms/AdsPage', icon: 'Megaphone', type: 'menu', sort: 12, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14141, parentId: 14140, title: '查询', type: 'button', permission: 'cms:ad:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14142, parentId: 14140, title: '管理广告', type: 'button', permission: 'cms:ad:manage', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14143, parentId: 14140, title: '查看广告事件', type: 'button', permission: 'cms:ad-event:list', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14144, parentId: 14140, title: '导出广告事件', type: 'button', permission: 'cms:ad-event:export', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14145, parentId: 14140, title: '清理广告事件', type: 'button', permission: 'cms:ad-event:cleanup', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14146, parentId: 14140, title: '导出广告原始明细', type: 'button', permission: 'cms:ad-event:export-raw', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14150, parentId: 14000, title: '表单管理', name: 'CmsForms', path: '/cms/forms', component: 'cms/FormsPage', icon: 'ClipboardList', type: 'menu', sort: 13, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14151, parentId: 14150, title: '查询', type: 'button', permission: 'cms:form:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14152, parentId: 14150, title: '管理表单', type: 'button', permission: 'cms:form:manage', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14160, parentId: 14000, title: '敏感词库', name: 'CmsSensitiveWords', path: '/cms/sensitive-words', component: 'cms/SensitiveWordsPage', icon: 'ShieldAlert', type: 'menu', sort: 14, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14161, parentId: 14160, title: '查询', type: 'button', permission: 'cms:sensitive:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14162, parentId: 14160, title: '管理敏感词', type: 'button', permission: 'cms:sensitive:manage', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14170, parentId: 14000, title: '采集中心', name: 'CmsCollect', path: '/cms/collect', component: 'cms/CollectPage', icon: 'Download', type: 'menu', sort: 15, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14171, parentId: 14170, title: '查询', type: 'button', permission: 'cms:collect:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14172, parentId: 14170, title: '新增规则', type: 'button', permission: 'cms:collect:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14173, parentId: 14170, title: '编辑规则', type: 'button', permission: 'cms:collect:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14174, parentId: 14170, title: '删除规则', type: 'button', permission: 'cms:collect:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14175, parentId: 14170, title: '执行采集', type: 'button', permission: 'cms:collect:run', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14300, parentId: 14000, title: '页面部件', name: 'CmsWidgets', path: '/cms/widgets', component: 'cms/WidgetsPage', icon: 'PanelsTopLeft', type: 'menu', sort: 16, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14301, parentId: 14300, title: '查询', type: 'button', permission: 'cms:widget:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14302, parentId: 14300, title: '新增部件', type: 'button', permission: 'cms:widget:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14303, parentId: 14300, title: '编辑部件', type: 'button', permission: 'cms:widget:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14304, parentId: 14300, title: '发布部件', type: 'button', permission: 'cms:widget:publish', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14305, parentId: 14300, title: '下线部件', type: 'button', permission: 'cms:widget:offline', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14306, parentId: 14300, title: '删除部件', type: 'button', permission: 'cms:widget:delete', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14307, parentId: 14300, title: '绑定主题插槽', type: 'button', permission: 'cms:widget:bind', sort: 6, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14310, parentId: 14300, title: '页面部件编辑', name: 'CmsWidgetEdit', path: '/cms/widgets/edit', component: 'cms/WidgetEditPage', icon: 'SquarePen', type: 'menu', sort: 7, status: 'enabled', visible: false, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14311, parentId: 14310, title: '查询', type: 'button', permission: 'cms:widget:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14180, parentId: 14000, title: '页面搭建', name: 'CmsPages', path: '/cms/pages', component: 'cms/PagesPage', icon: 'LayoutTemplate', type: 'menu', sort: 17, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14181, parentId: 14180, title: '查询', type: 'button', permission: 'cms:page:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14182, parentId: 14180, title: '新增页面', type: 'button', permission: 'cms:page:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14183, parentId: 14180, title: '编辑页面', type: 'button', permission: 'cms:page:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14184, parentId: 14180, title: '删除页面', type: 'button', permission: 'cms:page:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14185, parentId: 14180, title: '管理区块权限', type: 'button', permission: 'cms:page:acl', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14200, parentId: 14000, title: '易错词库', name: 'CmsErrorProneWords', path: '/cms/error-prone-words', component: 'cms/ErrorProneWordsPage', icon: 'SpellCheck', type: 'menu', sort: 18, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14201, parentId: 14200, title: '查询', type: 'button', permission: 'cms:word:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14202, parentId: 14200, title: '管理易错词', type: 'button', permission: 'cms:word:manage', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14210, parentId: 14000, title: '互动问卷', name: 'CmsInteractions', path: '/cms/interactions', component: 'cms/SurveysPage', icon: 'ListChecks', type: 'menu', sort: 19, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14211, parentId: 14210, title: '查询', type: 'button', permission: 'cms:interaction:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14212, parentId: 14210, title: '管理互动问卷', type: 'button', permission: 'cms:interaction:manage', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14213, parentId: 14210, title: '批量流转互动', type: 'button', permission: 'cms:interaction:batch', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14214, parentId: 14210, title: '导出互动答卷', type: 'button', permission: 'cms:interaction:export', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14215, parentId: 14210, title: '导出互动原始答卷', type: 'button', permission: 'cms:interaction:export-raw', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14216, parentId: 14210, title: '互动问卷设计页', name: 'CmsInteractionEdit', path: '/cms/interactions/edit', component: 'cms/interaction/InteractionEditPage', icon: 'PencilRuler', type: 'menu', sort: 5, status: 'enabled', visible: false, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14217, parentId: 14216, title: '查询', type: 'button', permission: 'cms:interaction:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14220, parentId: 14000, title: '访问统计', name: 'CmsStats', path: '/cms/stats', component: 'cms/StatsPage', icon: 'ChartLine', type: 'menu', sort: 20, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14221, parentId: 14220, title: '查询', type: 'button', permission: 'cms:stat:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14240, parentId: 14000, title: '发布中心', name: 'CmsPublishing', path: '/cms/publishing', component: 'cms/PublishingPage', icon: 'Rocket', type: 'menu', sort: 22, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14241, parentId: 14240, title: '查询', type: 'button', permission: 'cms:publish:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14242, parentId: 14240, title: '管理发布任务', type: 'button', permission: 'cms:publish:manage', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14250, parentId: 14000, title: '会员订阅', name: 'CmsSubscriptions', path: '/cms/subscriptions', component: 'cms/SubscriptionsPage', icon: 'BellRing', type: 'menu', sort: 23, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14251, parentId: 14250, title: '查询', type: 'button', permission: 'cms:subscription:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14252, parentId: 14250, title: '导出订阅明细', type: 'button', permission: 'cms:subscription:export', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14253, parentId: 14250, title: '导出订阅原始明细', type: 'button', permission: 'cms:subscription:export-raw', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14260, parentId: 14000, title: '内容分发', name: 'CmsDistribution', path: '/cms/distribution', component: 'cms/DistributionPage', icon: 'Network', type: 'menu', sort: 24, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14261, parentId: 14260, title: '查询', type: 'button', permission: 'cms:distribution:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14262, parentId: 14260, title: '新增分发规则', type: 'button', permission: 'cms:distribution:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14263, parentId: 14260, title: '编辑分发规则', type: 'button', permission: 'cms:distribution:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14264, parentId: 14260, title: '删除分发规则', type: 'button', permission: 'cms:distribution:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14265, parentId: 14260, title: '执行内容分发', type: 'button', permission: 'cms:distribution:run', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14266, parentId: 14260, title: '导出分发结果', type: 'button', permission: 'cms:distribution:export', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
];
