import type { Menu } from '../../identity/types';
import { SEED_DATE } from '../_base';

/** 会员中心（9000 段） */
export const SEED_MENUS_MEMBER: Menu[] = [
  { id: 9000, parentId: 0, title: '会员中心', name: 'MemberCenter', icon: 'Crown', type: 'directory', sort: 10, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9010, parentId: 9000, title: '会员看板', name: 'MemberDashboard', path: '/member/dashboard', component: 'member/MemberDashboardPage', icon: 'LayoutDashboard', type: 'menu', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9011, parentId: 9010, title: '查询', type: 'button', permission: 'member:dashboard:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9020, parentId: 9000, title: '会员管理', name: 'MemberList', path: '/member/members', component: 'member/MembersPage', icon: 'UserRound', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9021, parentId: 9020, title: '查询', type: 'button', permission: 'member:member:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9022, parentId: 9020, title: '新增会员', type: 'button', permission: 'member:member:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9023, parentId: 9020, title: '编辑会员', type: 'button', permission: 'member:member:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9024, parentId: 9020, title: '删除会员', type: 'button', permission: 'member:member:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9030, parentId: 9000, title: '会员等级', name: 'MemberLevels', path: '/member/levels', component: 'member/MemberLevelsPage', icon: 'Medal', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9031, parentId: 9030, title: '查询', type: 'button', permission: 'member:level:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9032, parentId: 9030, title: '新增等级', type: 'button', permission: 'member:level:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9033, parentId: 9030, title: '编辑等级', type: 'button', permission: 'member:level:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9034, parentId: 9030, title: '删除等级', type: 'button', permission: 'member:level:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9040, parentId: 9000, title: '积分管理', name: 'MemberPoints', path: '/member/points', component: 'member/MemberPointsPage', icon: 'Coins', type: 'menu', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9041, parentId: 9040, title: '查询', type: 'button', permission: 'member:point:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9042, parentId: 9040, title: '调整积分', type: 'button', permission: 'member:point:adjust', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9050, parentId: 9000, title: '钱包管理', name: 'MemberWallets', path: '/member/wallets', component: 'member/MemberWalletPage', icon: 'WalletCards', type: 'menu', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9051, parentId: 9050, title: '查询', type: 'button', permission: 'member:wallet:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9052, parentId: 9050, title: '调整余额', type: 'button', permission: 'member:wallet:adjust', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9053, parentId: 9050, title: '退款', type: 'button', permission: 'member:wallet:refund', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9060, parentId: 9000, title: '优惠券', name: 'Coupons', path: '/member/coupons', component: 'member/CouponsPage', icon: 'Ticket', type: 'menu', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9061, parentId: 9060, title: '查询', type: 'button', permission: 'member:coupon:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9062, parentId: 9060, title: '新增优惠券', type: 'button', permission: 'member:coupon:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9063, parentId: 9060, title: '编辑优惠券', type: 'button', permission: 'member:coupon:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9064, parentId: 9060, title: '删除优惠券', type: 'button', permission: 'member:coupon:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9065, parentId: 9060, title: '发放优惠券', type: 'button', permission: 'member:coupon:issue', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9066, parentId: 9060, title: '作废券码', type: 'button', permission: 'member:coupon:revoke', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9070, parentId: 9000, title: '领券记录', name: 'CouponRecords', path: '/member/coupon-records', component: 'member/CouponRecordsPage', icon: 'TicketCheck', type: 'menu', sort: 6, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9071, parentId: 9070, title: '查询', type: 'button', permission: 'member:coupon:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9080, parentId: 9000, title: '会员签到', name: 'MemberCheckin', icon: 'CalendarCheck', type: 'directory', sort: 7, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9090, parentId: 9080, title: '签到配置', name: 'CheckinRules', path: '/member/checkin-rules', component: 'member/CheckinRulesPage', icon: 'Settings', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9091, parentId: 9090, title: '查询', type: 'button', permission: 'member:checkin:rule:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9092, parentId: 9090, title: '新增规则', type: 'button', permission: 'member:checkin:rule:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9093, parentId: 9090, title: '编辑规则', type: 'button', permission: 'member:checkin:rule:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9094, parentId: 9090, title: '删除规则', type: 'button', permission: 'member:checkin:rule:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9095, parentId: 9090, title: '签到设置', type: 'button', permission: 'member:checkin:setting:update', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9100, parentId: 9080, title: '签到记录', name: 'CheckinLogs', path: '/member/checkin-logs', component: 'member/CheckinLogsPage', icon: 'CalendarDays', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9101, parentId: 9100, title: '查询', type: 'button', permission: 'member:checkin:log:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9102, parentId: 9100, title: '会员补签', type: 'button', permission: 'member:checkin:makeup', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9110, parentId: 9080, title: '里程碑配置', name: 'CheckinMilestones', path: '/member/checkin-milestones', component: 'member/CheckinMilestonesPage', icon: 'Trophy', type: 'menu', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9111, parentId: 9110, title: '查询', type: 'button', permission: 'member:checkin:milestone:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9112, parentId: 9110, title: '新增里程碑', type: 'button', permission: 'member:checkin:milestone:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9113, parentId: 9110, title: '编辑里程碑', type: 'button', permission: 'member:checkin:milestone:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9114, parentId: 9110, title: '删除里程碑', type: 'button', permission: 'member:checkin:milestone:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9120, parentId: 9000, title: '登录日志', name: 'MemberLoginLogs', path: '/member/login-logs', component: 'member/MemberLoginLogsPage', icon: 'LogIn', type: 'menu', sort: 8, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9121, parentId: 9120, title: '查询', type: 'button', permission: 'member:loginlog:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9130, parentId: 9000, title: '充值记录', name: 'MemberRecharges', path: '/member/recharges', component: 'member/MemberRechargesPage', icon: 'CreditCard', type: 'menu', sort: 9, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 9131, parentId: 9130, title: '查询', type: 'button', permission: 'member:recharge:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },

  // ─── 公众号管理（10000 段）
];
