import type { Menu } from '../../identity/contracts';
import { SEED_DATE } from '../_base';

/** 公众号管理（10000 段） */
export const SEED_MENUS_MP: Menu[] = [
  { id: 10000, parentId: 0, title: '公众号管理', name: 'MpCenter', icon: 'MessageCircle', type: 'directory', sort: 11, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10010, parentId: 10000, title: '公众号账号', name: 'MpAccounts', path: '/mp/accounts', component: 'mp/MpAccountsPage', icon: 'BadgeCheck', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10011, parentId: 10010, title: '查询', type: 'button', permission: 'mp:account:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10012, parentId: 10010, title: '新增公众号', type: 'button', permission: 'mp:account:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10013, parentId: 10010, title: '编辑公众号', type: 'button', permission: 'mp:account:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10014, parentId: 10010, title: '删除公众号', type: 'button', permission: 'mp:account:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10015, parentId: 10010, title: '设为默认', type: 'button', permission: 'mp:account:default', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10016, parentId: 10010, title: '测试连接', type: 'button', permission: 'mp:account:token', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10017, parentId: 10010, title: '内容安全检测', type: 'button', permission: 'mp:security:check', sort: 6, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10020, parentId: 10000, title: '标签管理', name: 'MpTags', path: '/mp/tags', component: 'mp/MpTagsPage', icon: 'Tags', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10021, parentId: 10020, title: '查询', type: 'button', permission: 'mp:tag:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10022, parentId: 10020, title: '新增标签', type: 'button', permission: 'mp:tag:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10023, parentId: 10020, title: '编辑标签', type: 'button', permission: 'mp:tag:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10024, parentId: 10020, title: '删除标签', type: 'button', permission: 'mp:tag:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10025, parentId: 10020, title: '同步标签', type: 'button', permission: 'mp:tag:sync', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10030, parentId: 10000, title: '粉丝管理', name: 'MpFans', path: '/mp/fans', component: 'mp/MpFansPage', icon: 'Users', type: 'menu', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10031, parentId: 10030, title: '查询', type: 'button', permission: 'mp:fan:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10032, parentId: 10030, title: '同步粉丝', type: 'button', permission: 'mp:fan:sync', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10033, parentId: 10030, title: '编辑粉丝', type: 'button', permission: 'mp:fan:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10034, parentId: 10030, title: '会员绑定', type: 'button', permission: 'mp:fan:bind', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10035, parentId: 10030, title: '黑名单管理', type: 'button', permission: 'mp:fan:blacklist', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10040, parentId: 10000, title: '消息管理', name: 'MpMessages', path: '/mp/messages', component: 'mp/MpMessagesPage', icon: 'MessagesSquare', type: 'menu', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10041, parentId: 10040, title: '查询', type: 'button', permission: 'mp:message:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10042, parentId: 10040, title: '发送消息', type: 'button', permission: 'mp:message:send', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10050, parentId: 10000, title: '自动回复', name: 'MpAutoReplies', path: '/mp/auto-replies', component: 'mp/MpAutoRepliesPage', icon: 'Reply', type: 'menu', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10051, parentId: 10050, title: '查询', type: 'button', permission: 'mp:reply:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10052, parentId: 10050, title: '新增回复', type: 'button', permission: 'mp:reply:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10053, parentId: 10050, title: '编辑回复', type: 'button', permission: 'mp:reply:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10054, parentId: 10050, title: '删除回复', type: 'button', permission: 'mp:reply:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10060, parentId: 10000, title: '自定义菜单', name: 'MpMenu', path: '/mp/menu', component: 'mp/MpMenuPage', icon: 'Menu', type: 'menu', sort: 6, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10061, parentId: 10060, title: '查询', type: 'button', permission: 'mp:menu:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10062, parentId: 10060, title: '保存菜单', type: 'button', permission: 'mp:menu:save', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10063, parentId: 10060, title: '发布菜单', type: 'button', permission: 'mp:menu:publish', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10064, parentId: 10060, title: '拉取菜单', type: 'button', permission: 'mp:menu:pull', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10065, parentId: 10060, title: '删除菜单', type: 'button', permission: 'mp:menu:delete', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10070, parentId: 10000, title: '素材管理', name: 'MpMaterials', path: '/mp/materials', component: 'mp/MpMaterialsPage', icon: 'Image', type: 'menu', sort: 7, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10071, parentId: 10070, title: '查询', type: 'button', permission: 'mp:material:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10072, parentId: 10070, title: '新增素材', type: 'button', permission: 'mp:material:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10073, parentId: 10070, title: '重命名素材', type: 'button', permission: 'mp:material:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10074, parentId: 10070, title: '删除素材', type: 'button', permission: 'mp:material:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10075, parentId: 10070, title: '同步素材', type: 'button', permission: 'mp:material:sync', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10080, parentId: 10000, title: '图文草稿', name: 'MpDrafts', path: '/mp/drafts', component: 'mp/MpDraftsPage', icon: 'Newspaper', type: 'menu', sort: 8, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10081, parentId: 10080, title: '查询', type: 'button', permission: 'mp:draft:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10082, parentId: 10080, title: '新增图文', type: 'button', permission: 'mp:draft:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10083, parentId: 10080, title: '编辑图文', type: 'button', permission: 'mp:draft:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10084, parentId: 10080, title: '删除图文', type: 'button', permission: 'mp:draft:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10085, parentId: 10080, title: '推送图文', type: 'button', permission: 'mp:draft:push', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10090, parentId: 10000, title: '模板消息', name: 'MpTemplates', path: '/mp/template-messages', component: 'mp/MpTemplateMessagesPage', icon: 'MailCheck', type: 'menu', sort: 9, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10091, parentId: 10090, title: '查询', type: 'button', permission: 'mp:template:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10092, parentId: 10090, title: '同步模板', type: 'button', permission: 'mp:template:sync', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10093, parentId: 10090, title: '发送模板', type: 'button', permission: 'mp:template:send', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10094, parentId: 10090, title: '删除模板', type: 'button', permission: 'mp:template:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10100, parentId: 10000, title: '数据统计', name: 'MpStatistics', path: '/mp/statistics', component: 'mp/MpStatisticsPage', icon: 'BarChart3', type: 'menu', sort: 10, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10101, parentId: 10100, title: '查询', type: 'button', permission: 'mp:statistics:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10110, parentId: 10000, title: '群发消息', name: 'MpBroadcasts', path: '/mp/broadcasts', component: 'mp/MpBroadcastsPage', icon: 'Send', type: 'menu', sort: 11, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10111, parentId: 10110, title: '查询', type: 'button', permission: 'mp:broadcast:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10112, parentId: 10110, title: '新增群发', type: 'button', permission: 'mp:broadcast:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10113, parentId: 10110, title: '编辑群发', type: 'button', permission: 'mp:broadcast:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10114, parentId: 10110, title: '发送群发', type: 'button', permission: 'mp:broadcast:send', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10115, parentId: 10110, title: '删除群发', type: 'button', permission: 'mp:broadcast:delete', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10120, parentId: 10000, title: '带参二维码', name: 'MpQrcodes', path: '/mp/qrcodes', component: 'mp/MpQrcodesPage', icon: 'QrCode', type: 'menu', sort: 12, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10121, parentId: 10120, title: '查询', type: 'button', permission: 'mp:qrcode:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10122, parentId: 10120, title: '生成二维码', type: 'button', permission: 'mp:qrcode:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10123, parentId: 10120, title: '删除二维码', type: 'button', permission: 'mp:qrcode:delete', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10130, parentId: 10000, title: '网页授权', name: 'MpOAuth', path: '/mp/oauth', component: 'mp/MpOAuthPage', icon: 'KeyRound', type: 'menu', sort: 13, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10131, parentId: 10130, title: '查询', type: 'button', permission: 'mp:oauth:build', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10132, parentId: 10130, title: 'JS-SDK签名', type: 'button', permission: 'mp:jssdk:config', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10140, parentId: 10000, title: '多客服', name: 'MpKfAccounts', path: '/mp/kf-accounts', component: 'mp/MpKfAccountsPage', icon: 'Headphones', type: 'menu', sort: 14, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10141, parentId: 10140, title: '查询', type: 'button', permission: 'mp:kf:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10142, parentId: 10140, title: '添加客服', type: 'button', permission: 'mp:kf:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10143, parentId: 10140, title: '编辑客服', type: 'button', permission: 'mp:kf:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10144, parentId: 10140, title: '删除客服', type: 'button', permission: 'mp:kf:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10145, parentId: 10140, title: '同步客服', type: 'button', permission: 'mp:kf:sync', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10150, parentId: 10000, title: '会话工作台', name: 'MpKfSessions', path: '/mp/kf-sessions', component: 'mp/MpKfSessionsPage', icon: 'Headset', type: 'menu', sort: 15, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10151, parentId: 10150, title: '查询', type: 'button', permission: 'mp:kf:session:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10152, parentId: 10150, title: '接入会话', type: 'button', permission: 'mp:kf:session:accept', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10153, parentId: 10150, title: '转接会话', type: 'button', permission: 'mp:kf:session:transfer', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10154, parentId: 10150, title: '结束会话', type: 'button', permission: 'mp:kf:session:close', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10155, parentId: 10150, title: '会话回复', type: 'button', permission: 'mp:kf:session:reply', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10156, parentId: 10150, title: '路由配置', type: 'button', permission: 'mp:kf:session:config', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10160, parentId: 10000, title: '个性化菜单', name: 'MpConditionalMenus', path: '/mp/conditional-menus', component: 'mp/MpConditionalMenusPage', icon: 'ListTree', type: 'menu', sort: 16, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10161, parentId: 10160, title: '查询', type: 'button', permission: 'mp:condmenu:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10162, parentId: 10160, title: '新增菜单', type: 'button', permission: 'mp:condmenu:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10163, parentId: 10160, title: '编辑菜单', type: 'button', permission: 'mp:condmenu:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10164, parentId: 10160, title: '发布菜单', type: 'button', permission: 'mp:condmenu:publish', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10165, parentId: 10160, title: '删除菜单', type: 'button', permission: 'mp:condmenu:delete', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },

  // ─── 业务示例（11000 段）
];
