import type { Menu } from '../../identity/contracts';
import { SEED_DATE } from '../_base';

/** 支付中心（8000 段） */
export const SEED_MENUS_PAYMENT: Menu[] = [
  { id: 8000, parentId: 0, title: '支付中心', name: 'PaymentCenter', icon: 'Wallet', type: 'directory', sort: 9, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8010, parentId: 8000, title: '支付渠道', name: 'PaymentChannels', path: '/payment/channels', component: 'payment/PaymentChannelsPage', icon: 'CreditCard', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8011, parentId: 8010, title: '查询', type: 'button', permission: 'payment:channel:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8012, parentId: 8010, title: '新增渠道', type: 'button', permission: 'payment:channel:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8013, parentId: 8010, title: '编辑渠道', type: 'button', permission: 'payment:channel:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8014, parentId: 8010, title: '删除渠道', type: 'button', permission: 'payment:channel:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8020, parentId: 8000, title: '支付订单', name: 'PaymentOrders', path: '/payment/orders', component: 'payment/PaymentOrdersPage', icon: 'ScrollText', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8021, parentId: 8020, title: '查询', type: 'button', permission: 'payment:order:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8022, parentId: 8020, title: '发起支付', type: 'button', permission: 'payment:order:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8023, parentId: 8020, title: '关闭订单', type: 'button', permission: 'payment:order:close', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8024, parentId: 8020, title: '发起退款', type: 'button', permission: 'payment:order:refund', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8030, parentId: 8000, title: '退款记录', name: 'PaymentRefunds', path: '/payment/refunds', component: 'payment/PaymentRefundsPage', icon: 'Undo2', type: 'menu', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8031, parentId: 8030, title: '查询', type: 'button', permission: 'payment:refund:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8032, parentId: 8030, title: '退款审批', type: 'button', permission: 'payment:refund:approve', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8040, parentId: 8000, title: '回调日志', name: 'PaymentLogs', path: '/payment/logs', component: 'payment/PaymentLogsPage', icon: 'FileClock', type: 'menu', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8041, parentId: 8040, title: '查询', type: 'button', permission: 'payment:log:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8050, parentId: 8000, title: '对账中心', name: 'PaymentRecon', path: '/payment/recon', component: 'payment/PaymentReconPage', icon: 'FileCheck', type: 'menu', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8051, parentId: 8050, title: '查询', type: 'button', permission: 'payment:recon:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8052, parentId: 8050, title: '新建对账', type: 'button', permission: 'payment:recon:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8053, parentId: 8050, title: '删除对账', type: 'button', permission: 'payment:recon:delete', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8054, parentId: 8050, title: '处理差异', type: 'button', permission: 'payment:recon:handle', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8060, parentId: 8000, title: '资金台账', name: 'PaymentLedger', path: '/payment/ledger', component: 'payment/PaymentLedgerPage', icon: 'BookOpen', type: 'menu', sort: 6, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8061, parentId: 8060, title: '查询', type: 'button', permission: 'payment:ledger:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8062, parentId: 8060, title: '创建账户', type: 'button', permission: 'payment:ledger:account:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8063, parentId: 8060, title: '凭证过账', type: 'button', permission: 'payment:ledger:post', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8064, parentId: 8060, title: '凭证冲正', type: 'button', permission: 'payment:ledger:reverse', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8065, parentId: 8060, title: '预占管理', type: 'button', permission: 'payment:ledger:reserve', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8070, parentId: 8000, title: 'Webhook 订阅', name: 'PaymentWebhooks', path: '/payment/webhooks', component: 'payment/PaymentWebhooksPage', icon: 'Webhook', type: 'menu', sort: 7, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8071, parentId: 8070, title: '查询', type: 'button', permission: 'payment:webhook:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8072, parentId: 8070, title: '管理 Webhook', type: 'button', permission: 'payment:webhook:manage', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8080, parentId: 8000, title: '支付事件', name: 'PaymentEvents', path: '/payment/events', component: 'payment/PaymentEventsPage', icon: 'Activity', type: 'menu', sort: 8, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8081, parentId: 8080, title: '查询', type: 'button', permission: 'payment:ops:manage', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8090, parentId: 8000, title: '费率管理', name: 'PaymentFeeRules', path: '/payment/fee-rules', component: 'payment/PaymentFeeRulesPage', icon: 'Percent', type: 'menu', sort: 9, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8091, parentId: 8090, title: '查询', type: 'button', permission: 'payment:fee:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8092, parentId: 8090, title: '新增费率', type: 'button', permission: 'payment:fee:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8093, parentId: 8090, title: '编辑费率', type: 'button', permission: 'payment:fee:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8094, parentId: 8090, title: '删除费率', type: 'button', permission: 'payment:fee:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8100, parentId: 8000, title: '结算管理', name: 'PaymentSettlements', path: '/payment/settlements', component: 'payment/PaymentSettlementsPage', icon: 'Banknote', type: 'menu', sort: 10, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8101, parentId: 8100, title: '查询', type: 'button', permission: 'payment:settlement:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8102, parentId: 8100, title: '生成结算', type: 'button', permission: 'payment:settlement:generate', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8103, parentId: 8100, title: '标记结算', type: 'button', permission: 'payment:settlement:settle', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8110, parentId: 8000, title: '分账管理', name: 'PaymentSharing', path: '/payment/sharing', component: 'payment/PaymentSharingPage', icon: 'Split', type: 'menu', sort: 11, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8111, parentId: 8110, title: '查询', type: 'button', permission: 'payment:sharing:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8112, parentId: 8110, title: '接收方管理', type: 'button', permission: 'payment:sharing:manage', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8113, parentId: 8110, title: '发起分账', type: 'button', permission: 'payment:sharing:dispatch', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8120, parentId: 8000, title: '支付链接', name: 'PaymentLinks', path: '/payment/links', component: 'payment/PaymentLinksPage', icon: 'Link', type: 'menu', sort: 12, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8121, parentId: 8120, title: '查询', type: 'button', permission: 'payment:link:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8122, parentId: 8120, title: '新增链接', type: 'button', permission: 'payment:link:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8123, parentId: 8120, title: '编辑链接', type: 'button', permission: 'payment:link:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8124, parentId: 8120, title: '删除链接', type: 'button', permission: 'payment:link:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8130, parentId: 8000, title: '风控中心', name: 'PaymentRiskRules', path: '/payment/risk-rules', component: 'payment/PaymentRiskRulesPage', icon: 'ShieldAlert', type: 'menu', sort: 13, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8131, parentId: 8130, title: '查询', type: 'button', permission: 'payment:risk:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8132, parentId: 8130, title: '新增规则', type: 'button', permission: 'payment:risk:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8133, parentId: 8130, title: '编辑规则', type: 'button', permission: 'payment:risk:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8134, parentId: 8130, title: '删除规则', type: 'button', permission: 'payment:risk:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8135, parentId: 8130, title: '风控审核', type: 'button', permission: 'payment:risk:review', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8140, parentId: 8000, title: '支付方式', name: 'PaymentMethods', path: '/payment/methods', component: 'payment/PaymentMethodsPage', icon: 'Wallet', type: 'menu', sort: 14, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8141, parentId: 8140, title: '查询', type: 'button', permission: 'payment:method:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8142, parentId: 8140, title: '编辑方式', type: 'button', permission: 'payment:method:update', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8150, parentId: 8000, title: '财务报表', name: 'PaymentReports', path: '/payment/reports', component: 'payment/PaymentReportsPage', icon: 'ChartColumn', type: 'menu', sort: 15, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8151, parentId: 8150, title: '查询', type: 'button', permission: 'payment:report:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8160, parentId: 8000, title: '转账管理', name: 'PaymentTransfers', path: '/payment/transfers', component: 'payment/PaymentTransfersPage', icon: 'SendHorizontal', type: 'menu', sort: 16, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8161, parentId: 8160, title: '查询', type: 'button', permission: 'payment:transfer:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8162, parentId: 8160, title: '发起转账', type: 'button', permission: 'payment:transfer:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8163, parentId: 8160, title: '转账审批', type: 'button', permission: 'payment:transfer:approve', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8170, parentId: 8000, title: '应用管理', name: 'PaymentApps', path: '/payment/apps', component: 'payment/PaymentAppsPage', icon: 'LayoutGrid', type: 'menu', sort: 17, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8171, parentId: 8170, title: '查询', type: 'button', permission: 'payment:app:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8172, parentId: 8170, title: '管理应用', type: 'button', permission: 'payment:app:manage', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8180, parentId: 8000, title: '签约代扣', name: 'PaymentContracts', path: '/payment/contracts', component: 'payment/PaymentContractsPage', icon: 'Repeat', type: 'menu', sort: 18, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8181, parentId: 8180, title: '查询', type: 'button', permission: 'payment:contract:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8182, parentId: 8180, title: '协议操作', type: 'button', permission: 'payment:contract:manage', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8183, parentId: 8180, title: '计划管理', type: 'button', permission: 'payment:contract:plan', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8190, parentId: 8000, title: '交易投诉', name: 'PaymentDisputes', path: '/payment/disputes', component: 'payment/PaymentDisputesPage', icon: 'MessageSquareWarning', type: 'menu', sort: 19, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8191, parentId: 8190, title: '查询', type: 'button', permission: 'payment:dispute:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8192, parentId: 8190, title: '处理投诉', type: 'button', permission: 'payment:dispute:handle', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8200, parentId: 8000, title: '预授权', name: 'PaymentPreauths', path: '/payment/preauths', component: 'payment/PaymentPreauthsPage', icon: 'Snowflake', type: 'menu', sort: 20, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8201, parentId: 8200, title: '查询', type: 'button', permission: 'payment:preauth:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8202, parentId: 8200, title: '预授权操作', type: 'button', permission: 'payment:preauth:manage', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },

  // ─── 会员中心（9000 段）
];
