import type { Menu } from '../../identity/types';
import { SEED_DATE } from '../_base';

/** 报表中心（12000 段） */
export const SEED_MENUS_REPORT: Menu[] = [
  { id: 12000, parentId: 0, title: '报表中心', name: 'ReportCenter', icon: 'BarChart3', type: 'directory', sort: 13, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12010, parentId: 12000, title: '数据源', name: 'ReportDatasources', path: '/report/datasources', component: 'report/DataSourcesPage', icon: 'Database', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12011, parentId: 12010, title: '查询', type: 'button', permission: 'report:datasource:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12012, parentId: 12010, title: '新增数据源', type: 'button', permission: 'report:datasource:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12013, parentId: 12010, title: '编辑数据源', type: 'button', permission: 'report:datasource:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12014, parentId: 12010, title: '删除数据源', type: 'button', permission: 'report:datasource:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12020, parentId: 12000, title: '数据集', name: 'ReportDatasets', path: '/report/datasets', component: 'report/DatasetsPage', icon: 'Layers', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12021, parentId: 12020, title: '查询', type: 'button', permission: 'report:dataset:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12022, parentId: 12020, title: '新增数据集', type: 'button', permission: 'report:dataset:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12023, parentId: 12020, title: '编辑数据集', type: 'button', permission: 'report:dataset:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12024, parentId: 12020, title: '删除数据集', type: 'button', permission: 'report:dataset:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12030, parentId: 12000, title: '仪表盘', name: 'ReportDashboards', path: '/report/dashboards', component: 'report/DashboardListPage', icon: 'LayoutDashboard', type: 'menu', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12031, parentId: 12030, title: '查询', type: 'button', permission: 'report:dashboard:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12032, parentId: 12030, title: '新增仪表盘', type: 'button', permission: 'report:dashboard:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12033, parentId: 12030, title: '编辑仪表盘', type: 'button', permission: 'report:dashboard:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12034, parentId: 12030, title: '删除仪表盘', type: 'button', permission: 'report:dashboard:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12040, parentId: 12000, title: '订阅推送', name: 'ReportSubscriptions', path: '/report/subscriptions', component: 'report/SubscriptionsPage', icon: 'BellRing', type: 'menu', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12041, parentId: 12040, title: '查询', type: 'button', permission: 'report:subscription:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12042, parentId: 12040, title: '新增订阅', type: 'button', permission: 'report:subscription:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12043, parentId: 12040, title: '编辑订阅', type: 'button', permission: 'report:subscription:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12044, parentId: 12040, title: '删除订阅', type: 'button', permission: 'report:subscription:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12050, parentId: 12000, title: '打印报表', name: 'ReportPrintTemplates', path: '/report/print', component: 'report/PrintTemplatesPage', icon: 'Printer', type: 'menu', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12051, parentId: 12050, title: '查询', type: 'button', permission: 'report:print:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12052, parentId: 12050, title: '新增打印报表', type: 'button', permission: 'report:print:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12053, parentId: 12050, title: '编辑打印报表', type: 'button', permission: 'report:print:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12054, parentId: 12050, title: '删除打印报表', type: 'button', permission: 'report:print:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12060, parentId: 12000, title: '数据预警', name: 'ReportAlerts', path: '/report/alerts', component: 'report/AlertsPage', icon: 'BellPlus', type: 'menu', sort: 6, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12061, parentId: 12060, title: '查询', type: 'button', permission: 'report:alert:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12062, parentId: 12060, title: '新增预警', type: 'button', permission: 'report:alert:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12063, parentId: 12060, title: '编辑预警', type: 'button', permission: 'report:alert:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12064, parentId: 12060, title: '删除预警', type: 'button', permission: 'report:alert:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12070, parentId: 12000, title: '指标中心', name: 'ReportMetrics', path: '/report/metrics', component: 'report/MetricsPage', icon: 'Target', type: 'menu', sort: 7, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12071, parentId: 12070, title: '查询', type: 'button', permission: 'report:metric:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12072, parentId: 12070, title: '新增指标', type: 'button', permission: 'report:metric:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12073, parentId: 12070, title: '编辑指标', type: 'button', permission: 'report:metric:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12074, parentId: 12070, title: '删除指标', type: 'button', permission: 'report:metric:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12075, parentId: 12070, title: '评估指标', type: 'button', permission: 'report:metric:evaluate', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12076, parentId: 12070, title: '发布指标', type: 'button', permission: 'report:metric:publish', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12080, parentId: 12000, title: '数据质量', name: 'ReportQuality', path: '/report/quality', component: 'report/QualityPage', icon: 'BadgeCheck', type: 'menu', sort: 8, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12081, parentId: 12080, title: '查询', type: 'button', permission: 'report:dq:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12082, parentId: 12080, title: '新增质量规则', type: 'button', permission: 'report:dq:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12083, parentId: 12080, title: '编辑质量规则', type: 'button', permission: 'report:dq:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12084, parentId: 12080, title: '删除质量规则', type: 'button', permission: 'report:dq:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12085, parentId: 12080, title: '执行质量规则', type: 'button', permission: 'report:dq:run', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12086, parentId: 12080, title: '导出质量记录', type: 'button', permission: 'report:dq:export', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12090, parentId: 12000, title: '资源治理', name: 'ReportGovernance', path: '/report/governance', component: 'report/ReportGovernancePage', icon: 'ShieldCheck', type: 'menu', sort: 9, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12091, parentId: 12090, title: '查询', type: 'button', permission: 'report:folder:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12092, parentId: 12090, title: '新增资源目录', type: 'button', permission: 'report:folder:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12093, parentId: 12090, title: '编辑资源目录', type: 'button', permission: 'report:folder:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12094, parentId: 12090, title: '删除资源目录', type: 'button', permission: 'report:folder:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12095, parentId: 12090, title: '管理资源权限', type: 'button', permission: 'report:resource:acl', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12096, parentId: 12090, title: '查看有效权限', type: 'button', permission: 'report:resource:access', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12097, parentId: 12090, title: '转移资源所有权', type: 'button', permission: 'report:resource:transfer', sort: 6, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12098, parentId: 12090, title: '查看发布审批', type: 'button', permission: 'report:approval:list', sort: 7, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12099, parentId: 12090, title: '申请发布审批', type: 'button', permission: 'report:approval:request', sort: 8, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12100, parentId: 12090, title: '处理发布审批', type: 'button', permission: 'report:approval:approve', sort: 9, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12101, parentId: 12090, title: '查看报表环境', type: 'button', permission: 'report:environment:list', sort: 10, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12102, parentId: 12090, title: '新增报表环境', type: 'button', permission: 'report:environment:create', sort: 11, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12103, parentId: 12090, title: '编辑报表环境', type: 'button', permission: 'report:environment:update', sort: 12, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12104, parentId: 12090, title: '删除报表环境', type: 'button', permission: 'report:environment:delete', sort: 13, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12105, parentId: 12090, title: '环境发布回滚', type: 'button', permission: 'report:environment:promote', sort: 14, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12106, parentId: 12090, title: '查看物化快照', type: 'button', permission: 'report:materialization:list', sort: 15, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12107, parentId: 12090, title: '刷新物化快照', type: 'button', permission: 'report:materialization:refresh', sort: 16, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12108, parentId: 12090, title: '清理物化快照', type: 'button', permission: 'report:materialization:purge', sort: 17, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12109, parentId: 12090, title: '查看查询配额', type: 'button', permission: 'report:query-quota:list', sort: 18, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12110, parentId: 12090, title: '新增查询配额', type: 'button', permission: 'report:query-quota:create', sort: 19, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12111, parentId: 12090, title: '编辑查询配额', type: 'button', permission: 'report:query-quota:update', sort: 20, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12112, parentId: 12090, title: '删除查询配额', type: 'button', permission: 'report:query-quota:delete', sort: 21, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12113, parentId: 12090, title: '查看查询成本', type: 'button', permission: 'report:query-cost:list', sort: 22, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12114, parentId: 12090, title: '查看 SLA', type: 'button', permission: 'report:sla:list', sort: 23, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12115, parentId: 12090, title: '新增 SLA', type: 'button', permission: 'report:sla:create', sort: 24, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12116, parentId: 12090, title: '编辑 SLA', type: 'button', permission: 'report:sla:update', sort: 25, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12117, parentId: 12090, title: '删除 SLA', type: 'button', permission: 'report:sla:delete', sort: 26, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12118, parentId: 12090, title: '评估 SLA', type: 'button', permission: 'report:sla:evaluate', sort: 27, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12119, parentId: 12090, title: '导出查询成本', type: 'button', permission: 'report:query-cost:export', sort: 28, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12120, parentId: 12000, title: '资产目录', name: 'ReportAssets', path: '/report/assets', component: 'report/AssetsPage', icon: 'Library', type: 'menu', sort: 10, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12121, parentId: 12120, title: '查询', type: 'button', permission: 'report:asset:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12122, parentId: 12120, title: '查看资产用量', type: 'button', permission: 'report:asset:usage', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12123, parentId: 12120, title: '查看弃用公告', type: 'button', permission: 'report:deprecation:list', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12124, parentId: 12120, title: '新增弃用公告', type: 'button', permission: 'report:deprecation:create', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12125, parentId: 12120, title: '编辑弃用公告', type: 'button', permission: 'report:deprecation:update', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12126, parentId: 12120, title: '发布弃用公告', type: 'button', permission: 'report:deprecation:publish', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12127, parentId: 12120, title: '删除弃用公告', type: 'button', permission: 'report:deprecation:delete', sort: 6, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12128, parentId: 12120, title: '查看资产模板', type: 'button', permission: 'report:asset-template:list', sort: 7, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12129, parentId: 12120, title: '新增资产模板', type: 'button', permission: 'report:asset-template:create', sort: 8, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12130, parentId: 12120, title: '编辑资产模板', type: 'button', permission: 'report:asset-template:update', sort: 9, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12131, parentId: 12120, title: '应用资产模板', type: 'button', permission: 'report:asset-template:apply', sort: 10, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12132, parentId: 12120, title: '删除资产模板', type: 'button', permission: 'report:asset-template:delete', sort: 11, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12133, parentId: 12120, title: '导出资产目录', type: 'button', permission: 'report:asset:export', sort: 12, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12140, parentId: 12000, title: '智能问数', name: 'ReportChatBi', path: '/report/chatbi', component: 'report/ChatBiPage', icon: 'MessageSquareText', type: 'menu', sort: 11, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12141, parentId: 12140, title: '查询', type: 'button', permission: 'report:chatbi:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12142, parentId: 12140, title: '创建问数会话', type: 'button', permission: 'report:chatbi:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12143, parentId: 12140, title: '编辑问数会话', type: 'button', permission: 'report:chatbi:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12144, parentId: 12140, title: '删除问数会话', type: 'button', permission: 'report:chatbi:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12145, parentId: 12140, title: '执行智能问数', type: 'button', permission: 'report:chatbi:ask', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12146, parentId: 12140, title: '保存问数结果', type: 'button', permission: 'report:chatbi:save', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12147, parentId: 12140, title: '查看问数审计', type: 'button', permission: 'report:chatbi:audit', sort: 6, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12148, parentId: 12140, title: '管理问数配额', type: 'button', permission: 'report:chatbi:manage', sort: 7, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12150, parentId: 12000, title: '填报模板', name: 'ReportFillTemplates', path: '/report/fill-templates', component: 'report/FillTemplatesPage', icon: 'ClipboardList', type: 'menu', sort: 12, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12151, parentId: 12150, title: '查询', type: 'button', permission: 'report:fill:template:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12152, parentId: 12150, title: '新增填报模板', type: 'button', permission: 'report:fill:template:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12153, parentId: 12150, title: '编辑填报模板', type: 'button', permission: 'report:fill:template:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12154, parentId: 12150, title: '发布/下线模板', type: 'button', permission: 'report:fill:template:publish', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12155, parentId: 12150, title: '克隆填报模板', type: 'button', permission: 'report:fill:template:clone', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12156, parentId: 12150, title: '删除填报模板', type: 'button', permission: 'report:fill:template:delete', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12160, parentId: 12000, title: '填报记录', name: 'ReportFillRecords', path: '/report/fill-records', component: 'report/FillRecordsPage', icon: 'ListChecks', type: 'menu', sort: 13, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12161, parentId: 12160, title: '查询', type: 'button', permission: 'report:fill:record:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12162, parentId: 12160, title: '创建填报记录', type: 'button', permission: 'report:fill:record:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12163, parentId: 12160, title: '编辑填报记录', type: 'button', permission: 'report:fill:record:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12164, parentId: 12160, title: '提交填报记录', type: 'button', permission: 'report:fill:record:submit', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12165, parentId: 12160, title: '撤回填报记录', type: 'button', permission: 'report:fill:record:cancel', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12166, parentId: 12160, title: '审核填报记录', type: 'button', permission: 'report:fill:record:review', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12167, parentId: 12160, title: '导出填报记录', type: 'button', permission: 'report:fill:record:export', sort: 6, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },

  // ─── 开放平台（13000 段）
];
