import type { Menu } from '../../identity/types';
import { SEED_DATE } from '../_base';

/** 系统管理（1000 段） */
export const SEED_MENUS_SYSTEM: Menu[] = [
  { id: 1000, parentId: 0, title: '系统管理', name: 'System', icon: 'Settings', type: 'directory', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1010, parentId: 1000, title: '用户管理', name: 'SystemUsers', path: '/system/users', component: 'users/UsersPage', icon: 'UsersRound', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1011, parentId: 1010, title: '查询', type: 'button', permission: 'system:user:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1012, parentId: 1010, title: '新增用户', type: 'button', permission: 'system:user:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1013, parentId: 1010, title: '编辑用户', type: 'button', permission: 'system:user:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1014, parentId: 1010, title: '删除用户', type: 'button', permission: 'system:user:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1015, parentId: 1010, title: '导入用户', type: 'button', permission: 'system:user:import', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1016, parentId: 1010, title: '导出用户', type: 'button', permission: 'system:user:export', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1017, parentId: 1010, title: '明文导出', type: 'button', permission: 'system:user:export-raw', sort: 6, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1018, parentId: 1010, title: '用户授权', type: 'button', permission: 'system:user:assign', sort: 7, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1020, parentId: 1000, title: '部门管理', name: 'SystemDepartments', path: '/system/departments', component: 'system/departments/DepartmentsPage', icon: 'Building2', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1021, parentId: 1020, title: '查询', type: 'button', permission: 'system:department:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1022, parentId: 1020, title: '新增部门', type: 'button', permission: 'system:department:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1023, parentId: 1020, title: '编辑部门', type: 'button', permission: 'system:department:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1024, parentId: 1020, title: '删除部门', type: 'button', permission: 'system:department:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1030, parentId: 1000, title: '岗位管理', name: 'SystemPositions', path: '/system/positions', component: 'system/positions/PositionsPage', icon: 'BriefcaseBusiness', type: 'menu', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1031, parentId: 1030, title: '查询', type: 'button', permission: 'system:position:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1032, parentId: 1030, title: '新增岗位', type: 'button', permission: 'system:position:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1033, parentId: 1030, title: '编辑岗位', type: 'button', permission: 'system:position:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1034, parentId: 1030, title: '删除岗位', type: 'button', permission: 'system:position:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1040, parentId: 1000, title: '菜单管理', name: 'SystemMenus', path: '/system/menus', component: 'system/menus/MenusPage', icon: 'LayoutList', type: 'menu', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1041, parentId: 1040, title: '查询', type: 'button', permission: 'system:menu:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1042, parentId: 1040, title: '新增菜单', type: 'button', permission: 'system:menu:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1043, parentId: 1040, title: '编辑菜单', type: 'button', permission: 'system:menu:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1044, parentId: 1040, title: '删除菜单', type: 'button', permission: 'system:menu:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1050, parentId: 1000, title: '用户组', name: 'SystemUserGroups', path: '/system/user-groups', component: 'system/user-groups/UserGroupsPage', icon: 'Users', type: 'menu', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1051, parentId: 1050, title: '查询', type: 'button', permission: 'system:user-groups:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1052, parentId: 1050, title: '新增用户组', type: 'button', permission: 'system:user-groups:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1053, parentId: 1050, title: '编辑用户组', type: 'button', permission: 'system:user-groups:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1054, parentId: 1050, title: '删除用户组', type: 'button', permission: 'system:user-groups:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1055, parentId: 1050, title: '分配成员', type: 'button', permission: 'system:user-groups:assign', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1060, parentId: 1000, title: '角色管理', name: 'SystemRoles', path: '/system/roles', component: 'system/roles/RolesPage', icon: 'ShieldCheck', type: 'menu', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1061, parentId: 1060, title: '查询', type: 'button', permission: 'system:role:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1062, parentId: 1060, title: '新增角色', type: 'button', permission: 'system:role:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1063, parentId: 1060, title: '编辑角色', type: 'button', permission: 'system:role:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1064, parentId: 1060, title: '删除角色', type: 'button', permission: 'system:role:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1065, parentId: 1060, title: '分配菜单', type: 'button', permission: 'system:role:assign', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1070, parentId: 1000, title: '字典管理', name: 'SystemDicts', path: '/system/dicts', component: 'system/dicts/DictsPage', icon: 'NotepadText', type: 'menu', sort: 6, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1071, parentId: 1070, title: '查询', type: 'button', permission: 'system:dict:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1072, parentId: 1070, title: '新增字典', type: 'button', permission: 'system:dict:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1073, parentId: 1070, title: '编辑字典', type: 'button', permission: 'system:dict:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1074, parentId: 1070, title: '删除字典', type: 'button', permission: 'system:dict:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1075, parentId: 1070, title: '管理字典项', type: 'button', permission: 'system:dict:item', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1080, parentId: 1000, title: '租户管理', name: 'SystemTenants', path: '/system/tenants', component: 'system/tenants/TenantsPage', icon: 'Building', type: 'menu', sort: 7, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1081, parentId: 1080, title: '查询', type: 'button', permission: 'system:tenant:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1082, parentId: 1080, title: '新增租户', type: 'button', permission: 'system:tenant:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1083, parentId: 1080, title: '编辑租户', type: 'button', permission: 'system:tenant:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1084, parentId: 1080, title: '删除租户', type: 'button', permission: 'system:tenant:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1090, parentId: 1000, title: '租户套餐', name: 'SystemTenantPackages', path: '/system/tenant-packages', component: 'system/tenant-packages/TenantPackagesPage', icon: 'Package', type: 'menu', sort: 7, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1091, parentId: 1090, title: '查询', type: 'button', permission: 'system:tenant-package:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1092, parentId: 1090, title: '新增套餐', type: 'button', permission: 'system:tenant-package:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1093, parentId: 1090, title: '编辑套餐', type: 'button', permission: 'system:tenant-package:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1094, parentId: 1090, title: '删除套餐', type: 'button', permission: 'system:tenant-package:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1095, parentId: 1090, title: '分配功能', type: 'button', permission: 'system:tenant-package:assign', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  // License 授权（与租户套餐同属授权治理；菜单本身是核心能力，受限模式下也必须可达）
  { id: 2660, parentId: 1000, title: 'License 授权', name: 'SystemLicense', path: '/system/license', component: 'system/license/LicensePage', icon: 'KeyRound', type: 'menu', sort: 7, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2661, parentId: 2660, title: '查询', type: 'button', permission: 'system:license:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2662, parentId: 2660, title: '激活/停用', type: 'button', permission: 'system:license:manage', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1100, parentId: 1000, title: '地区管理', name: 'SystemRegions', path: '/system/regions', component: 'system/regions/RegionsPage', icon: 'MapPin', type: 'menu', sort: 8, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1101, parentId: 1100, title: '查询', type: 'button', permission: 'system:region:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1102, parentId: 1100, title: '新增地区', type: 'button', permission: 'system:region:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1103, parentId: 1100, title: '编辑地区', type: 'button', permission: 'system:region:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1104, parentId: 1100, title: '删除地区', type: 'button', permission: 'system:region:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 1105, parentId: 1100, title: '导出地区', type: 'button', permission: 'system:region:export', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },

  // ─── 系统设置（2000 段）
];
